name: xpu-compile

on:
  pull_request:
    branches:
      - 'yizhou/compile_workflow'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

jobs:
  compile-tests:
    runs-on: [self-hosted, torch_compile_2]
    container:
      image: intel/intel-extension-for-pytorch:2.3.110-xpu
      ports:
        - 80
      options: --privileged -it --rm --device /dev/dri:/dev/dri -v /dev/dri/by-path:/dev/dri/by-path --ipc=host --cap-add=ALL

    steps:
    - uses: actions/checkout@v4
    - name: Install prerequisite
      run: |
        pip install py-cpuinfo
        pip install .[dev,autotuning]

    - name: Check container state
      run: |
        ldd --version
        ds_report
        python3 -c "import torch; print('torch:', torch.__version__, torch)"
        python3 -c "import torch; import intel_extension_for_pytorch; print('XPU available:', torch.xpu.is_available())"
        python3 -c "from deepspeed.accelerator import get_accelerator; print('accelerator:', get_accelerator()._name)"
        pip list

    - name: Compile Status
      run: |
        export CCL_ROOT=${CONDA_PREFIX}
        cd tests/torch_compile
        export ZE_AFFINITY_MASK=0,1
        deepspeed compile_graph_break.py --deepspeed_config ds_config.json 2>&1 | tee log.txt
        GITHUB_STEP_SUMMARY=$(cat log.txt |  grep "'graph_breaks'" | sed 's/,/ /g' | awk '{print $2}')